# Generated by Django 5.0.3 on 2024-05-02 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_animations_favs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animations',
            name='video',
            field=models.FileField(null=True, upload_to='animations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
