# Generated by Django 5.0.3 on 2024-05-03 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_video_delete_animations'),
    ]

    operations = [
        migrations.CreateModel(
            name='animations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('video', models.FileField(null=True, upload_to='animations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
